cask_args appdir: "/Applications"

tap "caskroom/cask"

brew "coreutils"
brew "ctags"
brew "curl"
brew "elixir"
brew "git"
brew "go"
brew "awsclient"
brew "heroku"
brew "htop-osx"
brew "hub"
brew "imagemagick"
brew "yarn"
brew "postgresql", service_restart: true
brew "redis", service_restart: true
brew "asdf"
brew "the_silver_searcher"
brew "tldr"
brew "unrar"
brew "wget"
brew "zsh"
brew "vim"
brew "git-crypt"

cask "1password"
cask "caffeine"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "numi"
cask "skype"
cask "slack"
cask "spotify"
